### PR TITLE
Loading dataset

### PR DESCRIPTION
**Pull request by Alessio-Olivieri**
Hello bros i'm learning to use github!!!

Please help me with this serious intensive task

### CODE REVIEW

**Comment by Alessio-Olivieri** [comment]
please approve :)

**Review by ami-sc — APPROVED** [review]
Looks good to me!

**Comment by Alessio-Olivieri** [comment]
I made a script to fix an image in the fire dataset which was corrupted for me.
It will delete the corrupted image and keep consistency within the enumeration of the various images

**Comment by Alessio-Olivieri** [comment]
the script didn't work

**Comment by Alessio-Olivieri** [comment]
Now it does!

**Review by mediolanum1 — APPROVED** [review]

**Comment by mediolanum1** [comment]
I like it

**Pull request merged**
